name: e2etest
on:
  [workflow_dispatch]
  #push:
  #branches: [main, master]
  #pull_request:
  #branches: [main, master]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      # リポジトリチェックアウト
      - name: Checkout Repo TODO-APP
        uses: actions/checkout@v4
        with:
          repository: KobayashiAnzu/TODO-APP
          #ref: ${{ github.event.pull_request.head.sha }}
          path: ./TODO-APP

      # Node.jsをセットアップ（バージョンは最新のもの）
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # アプリケーションの依存関係をインストール
      - name: Install dependencies
        run: npm install -g yarn && yarn

      #Nodeプロジェクト起動
      - name: Start Node project
        run: npm start &
        working-directory: ./TODO-APP

      - name: Checkout Repo E2E-TEST
        uses: actions/checkout@v4
        with:
          repository: KobayashiAnzu/E2E-TEST

      # アプリケーションの依存関係をインストール
      - name: Install dependencies
        run: npm install -g yarn && yarn

      #playwrightインストール
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      #gaugeインストール
      - name: Install Gauge
        run: npm install -g @getgauge/cli

      #E2Eテスト実行
      - name: Run e2e tests
        run: yarn run:e2e
